Gladkikh_lab1
makometr/piaa_9383 pull request #3
Opened 2021-03-21 12:03 UTC by FollowJust

2021-03-23 01:59 UTC, makometr requested changes

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/graphic.py
> +y = [5229, 2216969, 14819233, 1360878045, 188898355755, 80554248332774, 2440483984772697]
откуда цифры?

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.h
> +    void set_cur_square_size(int value) { if(value > 0) cur_square_size_ = value; }
Почему среди паблик методов функции с разными стилем написания?

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.h
> +    void set_cur_square_size(int value) { if(value > 0) cur_square_size_ = value; }
как бы служебыне но как бы нет?

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.cpp
> +	if (x + cur_square_size_ > size_ || x < 0) { return; }
Отступ?

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.cpp
> +	if (x + cur_square_size_ > size_ || x < 0) { return; }
зачем фигкрные скобки?

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.cpp
> +	}
Ну ёмаё, что с отступами снова

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.cpp
> +}
И снова форматирование

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.h
> +    std::vector<std::vector<int>> arr_;
arr обычно вектор, не вектор веткоров

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.cpp
> +        }
Это лишнее, объяснишь на защите почему

2021-03-23 01:59 UTC, makometr commented on Gladkikh/lab1/source/Field.cpp
> +    return true;
Всё аналогично тому,что выше

2021-03-23 13:10 UTC, makometr commented
В тестах также ещё хорошо бы проверять невалидные данные, но пока и так хорошо

2021-03-23 14:39 UTC, FollowJust commented on Gladkikh/lab1/graphic.py
> +y = [5229, 2216969, 14819233, 1360878045, 188898355755, 80554248332774, 2440483984772697]
Запускал программу для всех чисел из массива X и записывал результат в массив Y. Этот файл нужен был только для того, чтобы график для исследования построить. Возможно, его не стоило загружать вовсе.

2021-03-23 14:45 UTC, FollowJust commented on Gladkikh/lab1/source/Field.h
> +    void set_cur_square_size(int value) { if(value > 0) cur_square_size_ = value; }
Мне в голову пришла дурацкая идея прочитать Google Code Style перед лабой. Всегда писал все в camelCase'е, но тут решил сделать "как надо". Ниже привел ссылку и цитату по именованию функций. Но в целом мне тоже не очень понравилось это, так что могу поменять и/или в дальнейшем вернутся к camelCase.

> Regular functions have mixed case; accessors and mutators may be named like variables.

[https://google.github.io/styleguide/cppguide.html#Function_Names](url)

2021-03-23 15:19 UTC, FollowJust commented
Насчет отступов - не знаю, в чем конкретно проблема, но есть подозрения, что дело в связке Windows + WSL (первое для написания программы, другое для тестов и для залития на гит) и особенностях line endings для файлов в системах. 
Вроде всё исправил.

2021-03-24 09:14 UTC, makometr commented on Gladkikh/lab1/graphic.py
> +y = [5229, 2216969, 14819233, 1360878045, 188898355755, 80554248332774, 2440483984772697]
Лучше автоматизировать это дело:)

2021-03-24 09:22 UTC, makometr commented on Gladkikh/lab1/source/Field.h
> +    void set_cur_square_size(int value) { if(value > 0) cur_square_size_ = value; }
Стиль написания, если он не ругилируется извне (как в с++), обычно является вкусовщиной и решением команды. Тут у меня возникла претензия к выдерживанию стиля: он может быть любой, но должен быть одинаков везде. За нахождение пункта правил - респект. Там всё-таки написано, что такое может практиковаться, т.е. это необязательно.

2021-03-26 16:08 UTC, makometr approved these changes

2021-03-26 16:08 UTC, merged