Mosin_lab3
makometr/piaa_9383 pull request #42
Opened 2021-05-04 14:40 UTC by KonstantinMosin

2021-05-08 12:56 UTC, makometr requested changes
Идея с апи и неиспользованием клсса неплоха, то названия для функций тоже надо в соотвествии с этим придумывать.
А надо все функции делать публичными?

отчёт - халява, файл с тестами есть, юнит-тестирования не увидел, в отчёте тоже про тесты ни слова

2021-05-08 12:56 UTC, makometr commented on Mosin/lab3/Source/API.cpp
> +std::pair<std::vector<char>, int> path(std::map<char, std::map<char, int>>& rGraph, char s, char t) {
Что path? Странное название для функции

2021-05-08 12:56 UTC, makometr commented on Mosin/lab3/Source/API.cpp
> +std::map<char, std::map<char, int>> transposition(std::map<char, std::map<char, int>>& graph) {
У тебя в фукции действия происходит, а имя функции - существительое

2021-05-08 12:56 UTC, makometr commented on Mosin/lab3/Source/API.cpp
> +std::pair<std::vector<char>, int> restore(std::map<char, std::pair<char, int>>& graph1, std::map<char, std::pair<char, int>>& graph2, char s, char t, char node) {
Что восстаналвиаем?

2021-05-10 09:11 UTC, KonstantinMosin commented
Исправлен отчет, скорректировано тестирование

2021-05-14 18:58 UTC, merged