Rybnikov lab1
makometr/piaa_9383 pull request #5
Opened 2021-03-21 21:35 UTC by RomanRybnikov

2021-03-23 01:35 UTC, makometr requested changes

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +using namespace std;
зло

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +	return 0;
Разный размер отступов

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +	}
Снова проблемы с форматированием

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +	std::list<Item> list;	// текущий список выложенных квадратов
Ну так и назови перемеенную `currSquaresList `или как-то так
и комментарий не нужен будет

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +	}
Если ты думаешь, что какой-то кусок кода сложен и трубет пояснений комментария, то вынести его в функцию с говорящим названием

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +	delete[] table;
Отступ

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +	if (N % 2 != 0) throw "N is not even";
Непоследовательное форматирование кода.
Это точно один человек писал?

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +bool PutItem(Item item, bool** table, int N, std::list<Item>& list, std::list<Item>& res,int nMax) // попытка добавить еще один итем в текущую раскладку
Ну так если это попытка, то зачем функцию называть прямолинейно?

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +bool GetFirstEmpty(bool** table, int N, Position& position) // возвращает первую свободную позицию
вернуть FirstEmpty  ... что?
если бы комментария не было, не было и бы и понятно

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +void Add(bool** table, std::list<Item>& list, Item item) // добавляет указанный обрезок в раскладку
Add.... что?

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +void ShowTable(bool** table, int N) // вывод таблицы на экран (для дебага)
А если хочу вывсти в файл - ещё одну функцию писать?

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +	}
Если он уже вынесен и всё ещё непонятно, то либо неудачное название функции, либо функция требует разбиения

2021-03-23 01:35 UTC, makometr commented on Rybnikov/main.cpp
> +	}
Следующие комментарий не удаляй уже, но имей ввиду - комментировать каждую строку - неправильно, код должен сам за себя говорить (не всегда, но в большинстве случаев)

2021-03-24 20:43 UTC, RomanRybnikov commented
Залил исправления, но гит отказывается нормально принимать форматирование кода, и отстутпы все слетают..

2021-03-25 20:58 UTC, makometr commented on Rybnikov/main.cpp
> +void ShowTable(bool** table, int N) // вывод таблицы на экран (для дебага)
В ТЗ тоже не будет написано писать адекватный код. Это не ведь не означает, что писать его таким не нужно?

2021-03-25 21:03 UTC, RomanRybnikov commented on Rybnikov/main.cpp
> +void ShowTable(bool** table, int N) // вывод таблицы на экран (для дебага)
Понял, это учту. В исправлении я убрал эту функцию

2021-04-18 19:42 UTC, merged